### ISSUE TITLE
Mach-O template Section64 "offset" type should be uint32

### ISSUE THREAD

**Issue by secmobi** [strazzere/010Editor-stuff#15]
In the Mach-O template, the structure Section64 has an uint64 "offset" field:
https://github.com/strazzere/010Editor-stuff/blob/master/Templates/MachOTemplate.bt#L744

This Section64 is defined exactly the same with "section_64" in XNU header file:
https://opensource.apple.com/source/xnu/xnu-3248.60.10/EXTERNAL_HEADERS/mach-o/loader.h

However, in macOS's /usr/include/mach-o/loader.h, the section_64 was defined in a different way that "offset" is uint32_t. And there are three reserved fields appending other than two. LLVM project has the same definition:
http://llvm.org/docs/doxygen/html/Support_2MachO_8h_source.html

The MachOView used uint32_t for the field. Besides, I tried some real world samples, uint32 should be correct. By current uint64 template, __TEXT.__text's flag will be 0 and number of relocations will be a unreasonable huge number.

**Comment by strazzere** [comment]
Yes I actually ran into this issue yesterday while looking at a binary. However I'm not sure I follow the rest of your comment. The structs linked in other source files appear correct.

**Comment by secmobi** [comment]
The XNU source code is "uint32_t", which is correct. My first comment was wrong -- I misread the code.

**Comment by secmobi** [comment]
Btw, I think you should also add a "reserved3" field into Section64 to make its size to 80.
