### ISSUE TITLE
debug_info_off should deal correctly in the dex file template

### ISSUE THREAD

**Issue by jiych** [strazzere/010Editor-stuff#8]
there're some app packers set the debug_info_off filed to invalid value attentionly,such as 0xFFFFFFFF,we should deal this situation correctly.
![ac0befcb-4b92-4aef-9543-dd12d072aa30](https://cloud.githubusercontent.com/assets/1914451/9980256/1bcef4a2-5fc4-11e5-8a7a-35d83621a9d7.png)

**Comment by strazzere** [comment]
Ah, thanks - this is an easy fix. Can you provide the file you're looking at (sha256?) or at least the packer name?

Almost positive I can reproduce this regardless with the samples I already have, though I'd like to check it against what you're seeing exactly.

**Comment by jiych** [comment]
you can download the file here: https://www.dropbox.com/s/wqejn8m64za16ct/classes.dex?dl=0
it's a packer of tencent.

**Comment by strazzere** [comment]
Fixed in commit 85b7a78566f6b1e2d184978c4a4d3784ac7478a5
